### ISSUE TITLE
Why run the project will collapse?

### ISSUE THREAD

**Issue by zml5066** [mooncatventures-group/RTSPPlay#10]
I added a # define SDL_main main added sdl_sendquit the defined to resolve chain sdl_main and sql_sendquit mistakenly, but when I run a crash, all the settings are as you say, the collapse of the following figure:
![image](https://f.cloud.github.com/assets/3961196/326374/f1300ece-9b31-11e2-8ceb-042f72a39695.png)
My compiler environment xcode4.3, ios5.1 mac 10.7.5
I set a release

**Comment by mooncatventures-group** [comment]
Why do you have a mac tarket , this only runs on IOS.

Please re-pull project from git and this time don't change anything except

Remove armv7s arch if present in settings
remove the entitlement.plist reference from the settings
Set project type to release

Build for Release

Many people have built this project in the last few months.

**Comment by zml5066** [comment]
I re-download the project, open the project after the first experience entitlement.plist error in engineering, entitlement.plist this show deleted, and then in the code signing entitlements option Cary this entitlement.plis alsodeleted solve this problem, then I compiled encountered certificates issues, I changed the configuration of the certificate, the certificate problem solve the other nothing has changed, I once again compiled contains the problem encountered in the path, Ibefore to find the file in the project include path, one change over the last encounter sdl_main and sdl_sendquit defined error, I added the # define sdl_main solve two errors, and then real machine running crash problem is encountered,this is before me with the entire process of your project, I encountered path contains the problem, I was as you say, in addition to entitlement
![image](https://f.cloud.github.com/assets/3961196/331880/f7b4a41c-9c03-11e2-9228-5c430446011c.png)
How to solve these paths, I do not know, why would encounter these problems, I do not change

**Comment by mooncatventures-group** [comment]
you should not have to add defines, I don't know what your trying to do.
Send a log not screenprints

I added the # define sdl_main solve two errors, and then real machine

**Comment by zml5066** [comment]
Perhaps I did not make it clear that the problem now, and I re-download your project, and then as you say, how to keep the original, I now compiler encounters an error:
'FFPlayer / SDL_uikitappdelegate.h' file not found
'FFPlayer / SDL_uikitappdelegate.h 'file not found
