### ISSUE TITLE
How to play .3gp live url

### ISSUE THREAD

**Issue by trushalshah** [mooncatventures-group/RTSPPlay#3]
Hi, 
Thanks for this great script its working fine for me 

 when i am traying to play local url video with .3gp its working fine for me 
and while i replace with live url i am not able to play that video 
can you please help me , where i am doing wrong 

this are my local and live urls

rtsp://10.2.1.57/sample_50kbit.3gp
rtsp://180.211.106.106/WohLamhe-KyaMujhePyaarHai.3gp

**Comment by mooncatventures-group** [comment]
Did you try adding ?tcp to the end of the url

**Comment by mooncatventures-group** [comment]
The live script will play using rtspplay if you add ?tcp to then end of the url, the ffmpeg version .8.07 used with rtspplay uses ?tcp to force ffmpeg to stream over tcp.

We tested the stream with AVDemoPlay and AVDemoPlay2L, and they worked great playing using tcp. those two apps use the newer version of ffmpeg , rtspplay has not been built to use that newer version.
