### ISSUE TITLE
How to compile your project?

### ISSUE THREAD

**Issue by zml5066** [mooncatventures-group/RTSPPlay#6]
How to compile your project, I compiled when an error occurs, the error code
Undefined symbols for architecture armv7:
  "_SDL_main", referenced from:
      -[SDLUIKitDelegate postFinishLaunch:] in SDL_uikitappdelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by andida** [comment]
I meet the same problem!  how to slove it ? Thanks !

**Comment by mooncatventures-group** [comment]
please elaborate on what you are trying to do, include a log if possible
