### ISSUE TITLE
How to compile your project?

### ISSUE THREAD

**Issue by zml5066** [mooncatventures-group/RTSPPlay#7]
How to compile your project, I compiled when an error occurs, the error code
Undefined symbols for architecture armv7:
"_SDL_main", referenced from:
-[SDLUIKitDelegate postFinishLaunch:] in SDL_uikitappdelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mooncatventures-group** [comment]
we need to see more of the log, no one else reported issues like this.
were you trying to build the project as is or did you alter it, your project cannot
have its own main.m or main.c , sdl_main takes the place of these.

**Comment by mooncatventures-group** [comment]
does not run in debug , please use release
