### ISSUE TITLE
Why not complete your project

### ISSUE THREAD

**Issue by zml5066** [mooncatventures-group/RTSPPlay#8]
I download engineering lack Entitlements.plist, I copied The the info.plist renamed Entitlements.plist, but I do not know the original Entitlements.plist is what I would like to ask the works inside under Entitlements.plist in which download

**Comment by mooncatventures-group** [comment]
The project hasn't been updated in a while.

With new versions of xcode you must remove entitlements.plists completely, remove the file and remove the entry in settings.
You must also in settings remove armv7s arch. all phones will use armv7 without issue including iphone 5.
