### ISSUE TITLE
Compile your work has been

### ISSUE THREAD

**Issue by zml5066** [mooncatventures-group/RTSPPlay#9]
When I compile your engineering problems, as shown：
![image](https://f.cloud.github.com/assets/3961196/301908/f0564bc6-95f0-11e2-86b3-f9f48b246090.png)

My compiler environment:
xcode  4.0
ios4.3
macos 10.6.8

Why is it so？

my email zml5066@gmail.com

**Comment by mooncatventures-group** [comment]
Thanks, please try changing the run environment to release it
Looks like your running debug

**Comment by zml5066** [comment]
I do not know, you say debug or release environment, I use the debug environment, or the previous error, you said not to use xcode4.3 the ios5.1 target 3.1.2 environment
 replaced the debug or error:
![Uploading image.png . . .]()

**Comment by mooncatventures-group** [comment]
you must use release not debug

**Comment by zml5066** [comment]
I added a # define SDL_main main added sdl_sendquit the defined to resolve chain sdl_main and sql_sendquit mistakenly, but when I run a crash, all the settings are as you say, the collapse of the following figure:
![image](https://f.cloud.github.com/assets/3961196/322788/73f149d2-9a78-11e2-8748-a83fdc3bdb52.png)
My compiler environment xcode4.3, ios5.1 mac 10.7.5
I set a release

**Comment by mooncatventures-group** [comment]
duplicate
